= PVZDweb Frontend Web App und PEP

== Funktion

In PVZDweb sind die die Web Anwendungen Fedop, Portaladmin und Tnadmin enthalten, sowie der PEP.
Die Daten werden in einer externen Postgre-DB gespeichert


== Übersicht der Artefakte
 
Der Container beinhaltet folgende Objekte/Services/etc.:

|===
| Artefakt | Wert | Beschreibung
| APPHOME | /opt/PVZDweb | App Root Directory
| Django Konfiguration | pvzdweb/settings_<appname>
| Logging | STDOUT/STDERR |
| PEP Startscript | bin/pep.sh
| Service | django webapp | Anwendung je nach Django Konfiguration (INSTALLED_APPS)
|===


== Vorbereitung der Installation

Die Frontend-Webanwendungen sind mit je einem Docker Container vom Image pvzdweb realisiert.

Das Service wird über einen externen Proxy angebunden, der TLS terminiert (z.B. https://mdreg.portalverbund.gv.at).

Für die Kommunikation mit dem Backend Repo erfolgt über die Postgres-DB.


== Installation und Konfiguration PVZDweb

Dieser Arbeitsschritt orientiert sich am Ablauf des Jenkins Jobs.

Die 4 Instanzen von PVZDweb werden über das Django Settings Modul konfiguriert.
Dazu muss die Environment-Variable DJANGO_SETTINGS_MODULE im jeweiligen Service im Docker-Compose-File gesetzt werden.
Dann wird der Container mit einer Shell gestartet, um im Container die Django-Konfiguration anzupassen.
Sie ist persistent, weil das Verzeichnis /opt/PVZDweb/pvzdweb auf das Docker Volume pvzdweb.settings gemappt ist.

.Django Settings Dateien
|===
| DJANGO_SETTINGS_MODULE | Verwendung
|settings | Grundkonfiguration, wird von den anderen Settings erweitert
|settings_portaladmin | Portaladmin app
|settings_fedop | Zugriffsberechtigungen für Portaladmin (PMP)
|settings_pep | PEP
|settings_tnadmin | Teilnehmerverwaltung (TNV)
|===

.Django Settings Dateien (Entwicklung)
|===
| DJANGO_SETTINGS_MODULE | Verwendung
|settings_dev | Entwicklung, alle apps installiert
|settings_dev_tnadmin | Wie settings_dev, aber ohne portaladmin und JAVA-Abhängigkeiten
|settings.pytest_dev | Für Unittests: In-Memory-Datenbank
|===

In der Django Settings Datei sind folgende Einträge anzupassen:

|===
| Key | Verwendung
| DATABASE | Postgres und LDAP Parameter
| SECRET_KEY |  Installations-spezifischer Zufallswert (`openssl rand -base64 40`)
|===


== Logging

Die Webanwendung loggt auf stdout/stderr.
Die Logfiles werden außerhalb des Containers verwaltet, z.B. mit `docker logs` oder einem Logging Driver.

Der nginx-Proxy loggt auf /var/log/nginx.
Diese Files sind redundant und daher eher unwichtig.
Mit dem Script /scripts/nginx_logrotate.sh werden die Files rotiert und eine Generation aufbewahrt.
Das Script kann z.B. täglich aufgerufen werden.

== Beispielkonfiguration Webportal

Im Verzeichnis shibsp sind Beispiele zu Konfiguration eines PVP2-Proxy.