= PVZDweb Frontend Web App und PEP

== Funktion

Im Repo PVZDweb sind die die Web Anwendungen Fedop, Portaladmin und Tnadmin enthalten, sowie der PEP.
Die Daten werden in einer externen Postgre-DB gespeichert.


== Übersicht der Artefakte
 
Der Container beinhaltet folgende Objekte/Services/etc.:

|===
| Artefakt | Wert | Beschreibung
| APPHOME | /opt/PVZDweb | App Root Directory
| Django Konfiguration | pvzdweb/settings_<appname>
| Logging | STDOUT/STDERR |
| PEP Startscript | bin/pep.sh
| Service | django webapp | Anwendung je nach Django Konfiguration (INSTALLED_APPS)
|===


== Vorbereitung der Installation

Die Frontend-Webanwendungen und der PEP sind mit je einem Docker Container vom gleichen Image pvzdweb realisiert.
Das Frontend-Service wird über einen externen Proxy angebunden, der TLS terminiert (z.B. https://mdreg.portalverbund.gv.at).
Für die Kommunikation mit dem Backend Repo erfolgt über die Postgres-DB.


== Installation und Konfiguration PVZDweb

Dieser Arbeitsschritt orientiert sich am Ablauf des Jenkins Jobs.

Die 4 Instanzen von PVZDweb werden über Umgebungsvariablen konfiguriert.

Die Umgebungsvariablen werden in der docker-compose Konfiguration definiert und sind:

    * config.env  (DJANGO_SETTINGS_MODULE, DB- und Netzwerk-Parameter)
    * secrets.env (Schlüsselmaterial)


Dann wird der Container mit einer Shell gestartet, um innerhalb des Containers die Django-Konfiguration anzupassen.
Sie ist persistent, weil das Verzeichnis /opt/PVZDweb/pvzdweb auf das Docker Volume pvzdweb.settings gemappt ist.

.Django Settings Dateien
|===
| DJANGO_SETTINGS_MODULE | Verwendung
|settings_base | Grundkonfiguration, wird für das Deployment nicht angepasst
|settings | DB, Debug Mode
|settings_portaladmin | Portaladmin app
|settings_fedop | Zugriffsberechtigungen für Portaladmin (PMP)
|settings_pep | PEP
|settings_tnadmin | Teilnehmerverwaltung (TNV)
|===

.Django Settings Dateien (Entwicklung)
|===
| DJANGO_SETTINGS_MODULE | Verwendung
|settings_dev | Entwicklung, alle apps installiert
|settings_dev_tnadmin | Wie settings_dev, aber ohne portaladmin und JAVA-Abhängigkeiten
|settings.pytest_dev | Für Unittests: In-Memory-Datenbank
|===

In der Django Settings Datei sind folgende Einträge anzupassen:

|===
| Key | Verwendung
| DATABASE | Postgres und LDAP Parameter
| SECRET_KEY |  Installations-spezifischer Zufallswert (`openssl rand -base64 40`)
|===

== Authentifizierng

Die Authentifizierung erfolgt in der externen Infrastruktur per PVP.
Siehe das README von PVZDweb.
Die Anwendung benötigt dafür die UserId im HTTP Header X-PVP-USERID.
Der Name des Headers wird in SigProxyconfig.userid_http_header konfiguriert.


== Logging

Die Webanwendung loggt auf stdout/stderr.
Die Logfiles werden außerhalb des Containers verwaltet, z.B. mit `docker logs` oder einem Logging Driver.

Der nginx-Proxy loggt auf /var/log/nginx.
Diese logs sind weitgehend redundant und daher eher unwichtig.
Mit dem Script /opt/bin/rotate_logs.sh werden die Files entsprechend logrotate.conf rotiert.
Das Script sollte täglich aufgerufen werden, z.B.:

    docker.compose [-f config] exec <service> /opt/bin/rotate_logs.sh [-v]

== Fehlersuche

Der Aufruf der Webanwendung erfolgt über eine Proxy-Kaskade,
was bei der Fehlersuche ("500 internal server error" etc.) eine entsprechende Rücksicht erfordert.

Die Quellen für HTTP-codes >= 400 können an folgenden Stellen liegen:
1. Edge-Proxy
2. PVP-Reverse Proxy (wenn vorhanden)
3. Nginx im pvzdweb-Container  (/var/log/nginx)
4. Webserver/gunicorn (/var/log/webapp und /var/log/sigproxy)
5. Webapp/django (hat kein eigenes Logfile. Zur Fehlersuche muss DEBUG=Trie gesetzt werden,
   oder DJANGO_DEBUG für den Container.)
